### PR TITLE
update readme and userdoc to reflect current state of chrome extensio…

### PR DESCRIPTION
**Pull request by abhinavm24**
@adamlui feel free to change/merge as you see appropriate. Update the docs to reflect the chrome extension starter script since it's already on manifest v3

### CODE REVIEW

**Comment by adamlui** [comment]
Hey @abhinavm24 thanks for thinking of contributing, the steps you deleted are actually still needed to import chatgpt.js locally, so the change needed is either deleting the sentence "Since Google will [eventually phase out](https://developer.chrome.com/docs/extensions/migrating/mv2-sunset/) Manifest V2, remote code will no longer be allowed, so importing chatgpt.js locally is ideal:" or replacing it with "Since Google does not allow remote code, importing chatgpt.js locally is required:"

**Comment by abhinavm24** [comment]
Hey @adamlui the starter has the script already https://github.com/KudoAI/chatgpt.js-chrome-starter/blob/main/extension/lib/chatgpt.js
image

I can add still add "Since Google does not allow remote code, importing chatgpt.js locally" if you want

**Comment by adamlui** [comment]
@abhinavm24 yes it's best to add since not all will use starter, and the docs being edited are for chatgpt.js not the starter (chrome starter has its own instructions https://github.com/KudoAI/chatgpt.js-chrome-starter/tree/main/docs#readme that don't require user to follow 4 steps). But if you're feeling lazy, you can just delete the Manifest V2 sentence and go straight to steps (because otherwise you have to translate "Since Google does not allow remote code, importing chatgpt.js locally is required:" 13 times) and I can add that intro in the future

**Comment by abhinavm24** [comment]
Understood, Fixed

**Review by adamlui — APPROVED** [review]

**Pull request merged**
