### PR TITLE
Added `appendToSidebar`

### PR DESCRIPTION
**Pull request by madkarmaa**
~Work in progress~
Done!

### CODE REVIEW

**Comment by madkarmaa** [comment]
image
image

**Comment by madkarmaa** [comment]
I made the method return the `HTMLElement` instance so the user can do
```js
const select = chatgpt.appendToSidebar('select');
select.add(/* option HTML element here */);
```

**Review by adamlui — CHANGES_REQUESTED** [review]
You should change it to `appendButton()` and move to `chatgpt.sidebar` for a minimally viable version that takes these args: `(label, function, icon)`

Returning the element should be an optional bonus feature for styling, not a requirement because the expected core function is to run a passed function a click listener calls

**Review by adamlui — COMMENTED** [review]
Actually you could make it `chatgpt.sidebar.append(element, {options})` instead and start off w/ just make it work as `chatgpt.sidebar.append(button, { label: str, icon: src, callback: function })` what do you think? It's more organized for when support for other elements are added right?

**Comment by madkarmaa** [comment]
sure, I can make it like that

**Comment by adamlui** [comment]
and then I can eventually add short aliases like the chat methods for more versatility w/ easier calling like `chatgpt.appendButton(label, icon, callback)` that only take up a few lines

**Comment by madkarmaa** [comment]
as of now
```js
(async () => {
  await chatgpt.isLoaded();
  chatgpt.sidebar.append('button', { textContent: 'test' });
})();
```
is working fine
image

**Comment by madkarmaa** [comment]
```js
(async () => {
  await chatgpt.isLoaded();
  chatgpt.sidebar.append('select', { options: [{ text: 'banana', value: 'banana2' }] });
})();
```
image

**Comment by madkarmaa** [comment]
I'll add the icon stuff to the button

**Comment by adamlui** [comment]
> ```js
> (async () => {
>   await chatgpt.isLoaded();
>   chatgpt.sidebar.append('select', { options: [{ text: 'banana', value: 'banana2' }] });
> })();
> ```
> 
> image

That's great! Can you add a min height to the drop-down equal to button height? Also not so much nesting or need to type `options`? If you're planning on other options besides `options`, since they too are options they naturally belong in `options`, so you should rename current `options` to something like `items` and also ideally with an init like:

```js
const { label = 'ChatGPT Button', icon, callback // button options
        // selector options (including items)
} = options;
```

**Comment by adamlui** [comment]
That way as more element support is added, it is easy for both contributor to add inits + user to see how it works at top

**Comment by madkarmaa** [comment]
> Can you add a min height to the drop-down equal to button height?

isn't it inherited from the CSS classes that the method grabs? I think so

> If you're planning on other options besides `options`, since they too are options they naturally belong in `options`, so you should rename current `options` to something like `items`

sorry I'm not understanding what you're asking here

**Comment by adamlui** [comment]
When user types `chatgpt.sidebar.append('button' { options })` they fill options with key/values. When user types current `chatgpt.sidebar.append('selector', { options })` they also expect to fill it with key/values, but if one of the keys is `options` it is confusing (especially if they read the docs which will describe this 2nd arg 'options') since they don't expect to type 'options'. So you should name it after what kind of option it is (in this case, it's choices for the drop-down). And thee code example I gave should go as the first lines to make it easier to init defaults for other contributors (regardless of element)

**Comment by madkarmaa** [comment]
the parameter is indeed called differently, its name is `attrs`. in the code snippet, `options` is a list of items to add in the element when it is a `<select>`

**Comment by adamlui** [comment]
So you should call it `items` since that's what you even naturally called it, then in docs it won't be confusing vs. calling it 'options' which is used to refer to all options already. And you should still try to add the init near top like my example (you can insert arrays too)

Also remember I said I would make the feature tasklist long? Feast your eyes

image

**Comment by madkarmaa** [comment]
@adamlui is there anything else you want me to change/add?
```js
(async () => {
  await chatgpt.isLoaded();
  chatgpt.sidebar.append('button',
    {
      textContent: 'test',
      icon: 'https://raw.githubusercontent.com/adamlui/userscripts/master/chatgpt/media/icons/openai-favicon48.png'
    });
})();
```
image

**Review by adamlui — APPROVED** [review]
Ok good!

**Pull request merged**
