### PR TITLE
Added promise rejection to `chatgpt.getChatDetails()`

### PR DESCRIPTION
**Pull request by madkarmaa**

### CODE REVIEW

**Comment by madkarmaa** [comment]
I've added `reject` because if the user has no chats, the whole function fails with an unhandled error

**Comment by madkarmaa** [comment]
@adamlui what exactly you want me to add/fix?

**Comment by madkarmaa** [comment]
except for the docs, I'll make a commit to userguide.md once the method is completed

**Comment by adamlui** [comment]
> @adamlui what exactly you want me to add/fix?

the logic you described in the last pr details

> I can check if idx is a number and use it as a list index, else I do a for-loop to match the title or id with the respective title or id in the list items

image

(but with the right sub-obj)

**Comment by madkarmaa** [comment]
I don't know how you can work with stuff in light mode, I personally can't 💀

**Comment by adamlui** [comment]
Some sites dark mode like GitHub really don't work for me, also there's no rush since the method is minimally viable already, you can add it as a task if I enable the Projects tab and you can get familiar with project management if you want, lmk and I'll activate it

**Review by adamlui — APPROVED** [review]

**Pull request merged**
