### PR TITLE
Expanded flexibility of param passing to `getChatDetails()`

### PR DESCRIPTION
**Pull request by madkarmaa**
in `getAccountDetails` and `getChatDetails`

yeah, it works perfectly fine, but I assume you know better ways to achieve the same job, so check the code out.
in addition, by supplying multiple `detail` parameters the user is forced to also supply the `chat` parameter in `getChatDetails`

### CODE REVIEW

**Comment by madkarmaa** [comment]
also congrats for the big achievement 👏 

image

**Comment by adamlui** [comment]
> also congrats for the big achievement 👏
> 
> image

I can't believe the growth stlil didn't flatline (I literally stopped marketing it)

**Comment by madkarmaa** [comment]
> I can't believe the growth stlil didn't flatline (I literally stopped marketing it)

nah it's skyrocketing still 😂 

image

**Comment by madkarmaa** [comment]
this is why

image

you either -1 both `chat` and `data.length` or you don't

**Comment by adamlui** [comment]
> this is why
> 
> image
> 
> image
> 
> you either -1 both `chat` and `data.length` or you don't

nah it was fine as is, if data.length is 3 user supplies '3' for oldest chat, 3 !> 3 so is not out-of-bounds, then method gets index 2 and succeeds. if user supplies '4' for 4th chat, 4 > 3 so is out-of-bounds and correctly errors. If user supplies 1000, index 999 is out of bounds not 1000 so the removal of -1 is not rght

**Comment by adamlui** [comment]
because user seeking chat #1000 is index 999

**Comment by madkarmaa** [comment]
but you gotta remember the user's parameter starts from 1 and not 0, so to don't make it too complicated, we can just change the message to "is too big"

**Comment by madkarmaa** [comment]
else the user is going to think the last chat is (taking your example) 999 instead of 1000 (talking about parameter value, not list index)

**Comment by adamlui** [comment]
yes if user seeks 1000 then it's index 999 that's out of bounds not 1000, but indeed they can be confused so i'll fix the wording

**Comment by adamlui** [comment]
I'm also organizing it to be more user-friendly so don't wait up

image

**Comment by madkarmaa** [comment]
ye but how do we solve `chat` being forced to pass when multiple `detail` are supplied?

**Comment by adamlui** [comment]
> ye but how do we solve `chat` being forced to be passed when multiple `detail` are supplied?
> 
> also, use `chatgpt` instead of `this` to make it user friendly

I solved it in https://github.com/madkarmaa/chatgpt.js/commit/071e96c3109b632ad08d68570aa87b5996c30e7d can you try to break or improve it

**Comment by madkarmaa** [comment]
sure, I'll check it out tomorrow, it's almost 11pm right here and I'm going to sleep soon

**Pull request merged**
