### PR TITLE
Added `settings` object & fixed theme-related methods

### PR DESCRIPTION
**Pull request by madkarmaa**
and copied `scheme` object into it with spread syntax

idk if this is the approach you wanted, but it works perfectly fine

### CODE REVIEW

**Review by adamlui — CHANGES_REQUESTED** [review]
It's a start but as I mentioned the scheme methods themselves need replacing since they don't actually save any settings

**Comment by madkarmaa** [comment]
image
as simple as that, I found out that it's just a localStorage key, imma update the methods

**Comment by madkarmaa** [comment]
chatgpt.scheme is missing methods to set the theme dark/light, do you want me to add them?

**Comment by adamlui** [comment]
yes w/ .set('dark'|'light|'system')

**Comment by madkarmaa** [comment]
@adamlui it should be done now, give the code a look

**Review by adamlui — APPROVED** [review]
Great!

**Pull request merged**
