### PR TITLE
Added getChatDetails

### PR DESCRIPTION
**Pull request by madkarmaa**

### CODE REVIEW

**Comment by madkarmaa** [comment]
@adamlui nothing (it has default values). it's asynchronous, so you need to use `await` or `then()`

**Comment by adamlui** [comment]
Ok I'm making it more user friendly

**Comment by madkarmaa** [comment]
sure, make the `detail` parameter be one of these:

image

**Comment by adamlui** [comment]
@madkarmaa ok it's user-friendly now, the next logical step is to make it also allow supplying id (long string from detail) or title as the 1st arg. also i'm not merging yet because I have to setup a workflow to auto-update [kudoai/chatgpt.js-chrome-starter](https://github.com/kudoai/chatgpt.js-chrome-starter)'s lib code + version on all edits to chatgpt.js

**Comment by adamlui** [comment]
@madkarmaa you could also add it to userguide.md for when I finally style chatgpt.js.org to display it pretty and begin linking to it from main readme

**Comment by adamlui** [comment]
> sure, I'll add a first argument

@madkarmaa you mean to the function? it's a lot harder than it sounds, it has to allow user to supply index like it currently does, but also loop thru all conversations fetched to parse for 'title' match if title was supplied (or long string id if that's supplied)

**Comment by adamlui** [comment]
but if that's what you meant you were gonna do, to make it even more user friendly you should use partial matches via regex

**Comment by madkarmaa** [comment]
well it's not really that difficult. by destructuring what we need to do, I can check if `idx` is a number and use it as a list index, else I do a for-loop to match the title or id with the respective title or id in the list items

**Comment by adamlui** [comment]
but doing it with as few lines as possible is the hard part, if you can include partial matching case insensitively within a few lines then it would be perfect

**Comment by adamlui** [comment]
also regex should be used to auto-detect if it's a long string id (they all follow a certain format with hyphens)

**Comment by madkarmaa** [comment]
`if (idx === item.[title/id])` is not possible? 😂

**Comment by adamlui** [comment]
it certainly is if you don't make it user friendly, again i said making it partial match case insensitively for max user experience with few lines and regex as possible is the challenge (not that challenging for me but if you want to do it will take you much more time than you anticipate i predict)

**Comment by adamlui** [comment]
`===` is an exact match

**Comment by adamlui** [comment]
actually you can do the `===` and i can add the flexible matching

**Comment by madkarmaa** [comment]
I can use a ternary operator (condition ? true : false) like this:

```
toCheck = idx.test(idRegexp) ? 'id' : 'title'

...

if (idx === item[toCheck])
```

**Comment by adamlui** [comment]
i renamed idx to i btw but it should be renamed to chat since the arg is expanding, also item[toCheck] is not the right sub-obj it's actually nested one more (items.i.details)

**Comment by adamlui** [comment]
@madkarmaa it's updated in your fork

**Comment by adamlui** [comment]
(any changes made in your fork by anyone show up as commits in this pr)

**Comment by adamlui** [comment]
image

**Comment by adamlui** [comment]
@madkarmaa I just wrote an epic workflow https://github.com/kudoai/chatgpt.js/blob/main/.github/workflows/auto-sync-chatgpt.js-to-chrome-starter.yml I'm aching to test so i'ma merge now and you can create new pr

**Review by adamlui — APPROVED** [review]

**Pull request merged**
