### PR TITLE
Shortened responses-related methods

### PR DESCRIPTION
**Pull request by madkarmaa**
`getLastResponse()`, `getLastResponseDiv()`, `getResponse()`, `regenerate()` and `stop()` methods are now inside of `chatgpt.response`.

### CODE REVIEW

**Review by adamlui — CHANGES_REQUESTED** [review]
@madkarmaa for the style it's intentionally the original way because it's highly beneficial to have fewer lines since this project has no docs, user can more easily scroll thru lib to read each function for a general sense of what's possible (also the double-quotes will fail ESLint). If you revert the style changes and keep the response-related method revisions I can check it out though (probably easiest to start from original src again)

**Comment by adamlui** [comment]
@madkarmaa now that I read your comment, if you make the `chatgpt.response` without moving the original ones that would be great (that way user has more flexibility, one of the selling points and why this lib is popular I believe)

**Comment by madkarmaa** [comment]
I told you my formatting sucks 💀 anyways, tell me which formatter you use and its settings, so I can avoid all of this

**Comment by adamlui** [comment]
> I told you my formatting sucks 💀 anyways, tell me which formatter you use and its settings, so I can avoid all of this

Your formatting doesn't suck and is actually how most JS coders do it, but for this project's purpose it is not ideal since no docs exist but you can see the rules in https://github.com/kudoai/chatgpt.js/blob/main/.eslintrc.js

But you have a great idea of creating a new object for the response methods for more versatility

**Comment by adamlui** [comment]
@madkarmaa also you can just add the object in whatever style you want I can edit it

**Comment by adamlui** [comment]
@madkarmaa also there are two ways to approach it: for example, `chatgpt.response.regenerate()` could simply call `chatgpt.regenerate()`, or it could copy the original code over. The 1st way results in smaller filesize, while the 2nd way allows for future selective importing if I break lib into modules eventually + supports current modularity if user copies just that object in a local import (so doesn't need to copy the original functions). I think the 2nd way is ideal for how this lib is marketed (super versatility)

**Comment by adamlui** [comment]
> I personally think having objects is the best way, because no matter the versability, I actually think that having an object separating code that is related to something from the rest, is the best

Yes that is the 2nd way (don't copy original functions) and by not deleting original ones, it remains eveen more versatile because user can type `chatgpt.response.regenerate()` or `chatgpt.regenerateResponse()` (and my synonymizer further makes it more versatile by creating alias functions for original and new methods)

**Comment by adamlui** [comment]
(because not everyone prefers nested objects)

**Comment by madkarmaa** [comment]
also, I have a question. the `stop()` method, for example, has the same exact code of `getStopGeneratingButton()` with the addition of clicking the button. is this wanted or what? because I think it's just useless copied code

**Comment by madkarmaa** [comment]
ok how do I use `.eslintrc.js` bc it's almost the same but not the same

**Comment by adamlui** [comment]
What's your editor?

**Comment by madkarmaa** [comment]
Visual Studio Code

**Comment by adamlui** [comment]
In the plugins tab ESLint should be one of the top 5 shown, then click and install it, then when you open the chatgpt.js folder, errors will show up in the editor based on that folder's eslintrc.js

**Comment by adamlui** [comment]
That's weird, maybe restarting VSCode could fix, errors should show up in margins, also copyying the object into the original chatgpt.js is probably easiest (and don't worry about style I'll re-edit)

**Comment by adamlui** [comment]
You should copy/paste your new object into notepad, then discard all changes (not sure how in VS but in GitHub desktop, you right-click the commit > Discard changes), then you will have the original chatgpt.js again where you can paste the added obj

**Comment by adamlui** [comment]
It's OK with errors I'll re-edit

**Comment by adamlui** [comment]
but just for the obj, you should still revert to original chatgpt.js so it's faster for me to edit one obj

**Comment by madkarmaa** [comment]
I just committed once again, so I also changed the order to alphabetical order

**Comment by madkarmaa** [comment]
let's say I suck with github related stuff

**Comment by adamlui** [comment]
@madkarmaa it's ok I'll edit it after my curent task

**Pull request merged**
