### PR TITLE
Added getResponseFromAPI

### PR DESCRIPTION
**Pull request by madkarmaa**
I don't know if you want to _replace_ `getResponse` and `getLatestResponse` so I _added_ the method. I've supplied comments as well so you can understand more easily.

### CODE REVIEW

**Comment by adamlui** [comment]
@madkarmaa i'm making it more user friendly now

**Comment by madkarmaa** [comment]
also, is there any way to know if a function is called directly or not? I've been googling for a while and couldn't find anything. why this? because `getAccessToken` is used by multiple other functions, and it sucks to see the console being spammed by the log message, and I think it should only work if the function is called directly

**Comment by madkarmaa** [comment]
also (this is just an idea of mine), I think we should store an access token somewhere in the chatgpt object as a variable, and update it once it expires (the object has an expiration date, reference [here](https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L379)) to avoid getting rate limited by the api and reducing the speed of the library

**Comment by adamlui** [comment]
> also, is there any way to know if a function is called directly or not? I've been googling for a while and couldn't find anything. why this? because `getAccessToken` is used by multiple other functions, and it sucks to see the console being spammed by the log message, and I think it should only work if the function is called directly

yes using flags

**Comment by adamlui** [comment]
> also (this is just an idea of mine), I think we should store an access token somewhere in the chatgpt object as a variable, and update it once it expires (the token has an expiration date, reference [here](https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L379)) to avoid getting rate limited by the api and reducing the speed of the library
> 
> problem is idk about the security of doing this
> 
> edit: it shouldn't even matter since there's literally a function that retrieves the access token, so storing it in the object is not even a big deal, and removing the object from the window will literally make it disappear

can you separate this out into new issue

**Review by adamlui — APPROVED** [review]

**Comment by adamlui** [comment]
> > also (this is just an idea of mine), I think we should store an access token somewhere in the chatgpt object as a variable, and update it once it expires (the token has an expiration date, reference [here](https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L379)) to avoid getting rate limited by the api and reducing the speed of the library
> > problem is idk about the security of doing this
> > edit: it shouldn't even matter since there's literally a function that retrieves the access token, so storing it in the object is not even a big deal, and removing the object from the window will literally make it disappear
> 
> can you separate this out into new issue

Nvm I created it

**Comment by madkarmaa** [comment]
tomorrow I'll add docs for this, it's past 11pm and I'm going to sleep

**Pull request merged**
