### PR TITLE
Added id param value to the docs

### PR DESCRIPTION
**Pull request by madkarmaa**
P.S. I'm wondering if we could just return the object itself instead of a single detail

why? because let's say you want to `console.log` 2 account' details, email and image.
I think this
```js
const account = chatgpt.getAccountDetails();
console.log(account.email, account.image);
```
is better than this
```js
console.log(chatgpt.getAccountDetails('email'), chatgpt.getAccountDetails('image'));
```

### CODE REVIEW

**Comment by madkarmaa** [comment]
or, even better, if the detail is supplied, we return the detail, else we return the object by default

**Comment by adamlui** [comment]
Yes you should make it like that, you can use spread syntax to take unlimited parameters (chatgpt can explain it well I think)

**Comment by Krishnapatrl** [comment]
Good 😊

**Comment by adamlui** [comment]
If you look in my https://github.com/adamlui/chatgpt-widescreen and goto chrome/extension/lib/settings-util.js you can see example how I do it with loadSettings()

**Comment by madkarmaa** [comment]
ok, you can push this PR I'll create a new one since it'll have a different topic

**Comment by adamlui** [comment]
Also you should ignore the promise stuff in that function (it was required for chrome API) just the line for determining args is the one you should copy

**Review by adamlui — APPROVED** [review]

**Comment by adamlui** [comment]
@madkarmaa actually I forgot this is asumc so you should copy the promise logic too

**Comment by Krishnapatrl** [comment]
Dear, kudoai

I hope you are doing ❤️‍🩹

**Comment by adamlui** [comment]
@Krishnapatrl u da best

**Comment by Krishnapatrl** [comment]
Thank you for your response 😊

**Pull request merged**
