### PR TITLE
Added `menu.append`

### PR DESCRIPTION
**Pull request by madkarmaa**
```js
chatgpt.menu.append('button')
chatgpt.menu.append('dropdown')
```
image

### CODE REVIEW

**Comment by madkarmaa** [comment]
0 clue how to fix this, Idk about regex
image

**Review by adamlui — CHANGES_REQUESTED** [review]
The button works well but the dropdown notes don't really explain what items[] is can you explain it like that sidebar.append (also if you didn't actually do it there either and I overlooked it can you add the details there too) also for the regex you should just change it to a string to make error go away

**Comment by madkarmaa** [comment]
don't know where that 35% duplication is from _again_ but everything seems fine @adamlui

**Review by adamlui — CHANGES_REQUESTED** [review]
but text/value still isn't clear what it means in relation to the dropdown, also you should incorporate [] in some way to show the array of these objs

**Review by adamlui — APPROVED** [review]

**Pull request merged**
