### PR TITLE
Updated documentation as of commit d470bab

### PR DESCRIPTION
**Pull request by madkarmaa**
Some docs are still missing (reference #60 [here](https://github.com/kudoai/chatgpt.js/pull/60#issue-1794999696))

### CODE REVIEW

**Comment by madkarmaa** [comment]
you also got another 100 stars in 12 hours, come on

image

**Review by adamlui — APPROVED** [review]

**Comment by adamlui** [comment]
> you also got another 100 stars in 12 hours, come on
> 
> image

It's not forever it will stop eventualy

**Comment by madkarmaa** [comment]
> It's not forever it will stop eventualy

come on, you should be proud

**Comment by adamlui** [comment]
But I've seen spikes before, some influencer or site shares a repo, then traffic eventually flattens, but this has been going on for week so is highly unusual

**Comment by adamlui** [comment]
Analytics doesn't show any new traffic source either so I'm baffled

**Comment by madkarmaa** [comment]
so what, I font get any new source for my script yet I keep getting stars

**Comment by adamlui** [comment]
@madkarmaa it's because I listed it high due to alphabetization on chatgpt.js readme (I checked before, during moments when I thought chatgpt.js flatlined you didn't get stars, then what felt like a bum rush resulted in stars for you too)

**Comment by adamlui** [comment]
...so the mystery is solved, the source is GitHub itself

**Comment by adamlui** [comment]
They have fine tundled the algorithm in trying to emulate TikTok to recommend repos users are highly interested in

**Comment by adamlui** [comment]
They should add a source in traffic for if it came from recommendation

**Comment by madkarmaa** [comment]
yeah I was searching for readme ideas for my profile readme and now I keep getting recommend similar repos

**Pull request merged**
