### PR TITLE
getChatDetails now accepts chat IDs and titles

### PR DESCRIPTION
**Pull request by madkarmaa**

### CODE REVIEW

**Comment by adamlui** [comment]
Great!

**Review by adamlui — APPROVED** [review]

**Comment by adamlui** [comment]
@madkarmaa i always do before merge, it worked

**Comment by madkarmaa** [comment]
@adamlui i mean for code formatting, maybe there's shorter ways to write what I did

**Comment by adamlui** [comment]
@madkarmaa I improved it https://github.com/kudoai/chatgpt.js/commit/b38fee7aef440c4c1e12d98ef3eb065f294b103d

**Pull request merged**
