### PR TITLE
Shrank lang selector size (mobile)

### PR DESCRIPTION
**Pull request by madkarmaa**
to 80% of its original size

### CODE REVIEW

**Comment by madkarmaa** [comment]
img

**Comment by adamlui** [comment]
@madkarmaa the KudoAI logo is too small can you make them equal (and also test they're still equal in landscape)

**Comment by adamlui** [comment]
@madkarmaa can you align the selector to the right like desktop so it doesn't look crammed with KudoAI logo

**Comment by madkarmaa** [comment]
I didn't move it more because it would overlap with the GitHub corner

**Review by adamlui — APPROVED** [review]

**Pull request merged**
