### PR TITLE
hindi readme file updated

### PR DESCRIPTION
**Pull request by iamnishantgaharwar**

### CODE REVIEW

**Review by adamlui — COMMENTED** [review]
@iamnishantgaharwar for the showcase scripts, is there something wrong with the Hindi names?

**Comment by iamnishantgaharwar** [comment]
@adamlui i thought to keep all names consistent in english for all the scripts.

**Comment by adamlui** [comment]
> @adamlui i thought to keep all names consistent in english for all the scripts.

I see, the scripts that have Hindi names already use `// @name:hi` meta's from which they were copied, so Hindi users already know them by that name. Is there anything wrong with them? If so, can you correct them here and in the corresponding script repo? If not, can you revert?

**Comment by iamnishantgaharwar** [comment]
Ok so i will change all the names to hindi to make it consistent

**Comment by adamlui** [comment]
> Ok so i will change all the names to hindi to make it consistent

Ok but if the existing translation is good, then no change, but if it needs improvement, can you also change it in the original script's repo? (you can visit it by clicking title, then goto greasemonkey/script-name.user.js and change the `// @name:hi` value there to be the same change)

**Comment by adamlui** [comment]
@iamnishantgaharwar also is your Internet unlimited? If not I can copy your potential changes to the other repo's myself

**Comment by iamnishantgaharwar** [comment]
I have unlimited internet

**Comment by iamnishantgaharwar** [comment]
@adamlui done all name are in hindi

**Review by adamlui — APPROVED** [review]

**Comment by adamlui** [comment]
@iamnishantgaharwar check out https://github.com/kudoai/chatgpt.js/blob/main/docs/hi/SECURITY.md, anything needs improvement?

**Pull request merged**
