### PR TITLE
Docs updates

### PR DESCRIPTION
**Pull request by madkarmaa**

### CODE REVIEW

**Comment by madkarmaa** [comment]
not to merge yet

**Comment by adamlui** [comment]
> not to merge yet

then why'd you mark Done in tasklist (I changed it back)

**Comment by madkarmaa** [comment]
because that particular task is done

**Comment by adamlui** [comment]
it is not, look at all the `-` they have 4 spaecs after them now.. you can't just ctrl + h and call it a day, you have to manually do things like test yoru code examples that don't even work and are creating much more work for me

**Comment by adamlui** [comment]
if I could ctrl + h i wouldn't have made it a task. it's a task beacuse it's tedious conversion of code blocks only (you just did it to the whole doc with shortcut)

**Comment by madkarmaa** [comment]
wdym that they don't work

**Comment by adamlui** [comment]
the code doesn't store return value in anything so it is misleading to reader when you put in comment 'returns something'

**Comment by madkarmaa** [comment]
okay, I can modify the code blocks then, and no, I didn't use any shortcut lol

**Comment by adamlui** [comment]
Of course you did, the task was do it in code blocks, how can you explain its occurrence to whole documents indents

**Comment by adamlui** [comment]
You're suggesting you did not search/replace 2-space with 4-space which produces an identical result as your change?

**Comment by madkarmaa** [comment]
well I didn't know that, my bad, I've just enabled auto-formatting

**Comment by adamlui** [comment]
What auto-formatting

**Comment by madkarmaa** [comment]
> What auto-formatting

image

**Comment by adamlui** [comment]
So five keystrokes (ctrl + a  + c > ctrl + v) which is even fewer keystrokes than ctr + h > .... is not a shortcut in what way?

**Comment by adamlui** [comment]
You don't have to do anything, but everytime you do and take shortcuts it just derails my whole day because I spend so much time cleaning up after you. And you do it to look busy, it's not even fair you don't care about the quality of anything

**Comment by adamlui** [comment]
THat's why I'm dreading reviewing the append lol

**Comment by madkarmaa** [comment]
yeah ok

**Pull request closed without merging**
