### PR TITLE
Added status of chatgpt

### PR DESCRIPTION
**Pull request by mefengl**

### CODE REVIEW

**Comment by adamlui** [comment]
@mefengl hey how cum you deleted?

**Comment by mefengl** [comment]
🥹 I am unable to resolve the conflict in an elegant manner

**Comment by adamlui** [comment]
Do you mean conflict because I changed the file? If that is the only conflict you should re-open and I'll merge it

**Comment by mefengl** [comment]
I will recreate a pull request, don't worry

**Pull request closed without merging**
